application: linhdesign-1802
version: 1
runtime: go
api_version: go1

handlers:
- url: /fonts
  static_dir: fonts
  mime_type: "x-font-otf"
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images

- url: /.*
  script: _go_app
